Pom file updates
SchemaApp/AEMConnector pull request #6
Opened 2023-02-15 14:56 UTC by nikhilajudiya

# type(scope): if this commit is applied, it will...
i.e. fix(login): [more detailed message]

# Why was this change made?

Feature request? A bug was found? Doing some refactoring? Let us know why this should be in our codebase.

# Links to any relevant tickets, articles, or other resources

closes https://github.com/SchemaApp/SchemaApp/issues/11869 
closes https://github.com/SchemaApp/SchemaApp/issues/11868 
# Other Notes

Did you fix any additional issues or do you have special notes for the reviewer? Put them here.

# Suggested Test for Reviewer

1. Login to Schema app dashboard
2. Go to 
3. Do action
4. See result

2023-02-15 21:13 UTC, joelacummings requested changes
I'm noticing a problem when there is highlight.js and editor markup for the page. I don't see it pulling in highlight.js markup for the the homepage on our test environment. I think there is an issue around this. If there is markup under __highlighter_js and under the base directory it can either combine them or it can include two separate json-ld blocks. 

There is also a codacy around instantiating string objects.

2023-02-20 12:43 UTC, nikhilajudiya commented
Hi @joelacummings I can see JSONL-D added correct for home page - 
![image](https://user-images.githubusercontent.com/13587090/220111662-b40843c6-4a9a-4f5c-b42b-44ccf37cdfb9.png)

2023-02-22 21:46 UTC, joelacummings requested changes
Manual testing was fine, code needs to have docstrings and we need a release version.

2023-02-22 21:46 UTC, joelacummings commented on all/pom.xml
> +        <version>1.0.7-SNAPSHOT</version>
Can we make this 1.4 and not a snapshot so we can release this more broadly?

2023-02-22 21:46 UTC, joelacummings commented on core/src/main/java/com/schemaapp/core/services/impl/CDNDataAPIServiceImpl.java
> +    private Object processJavaScriptCDNData(
add a docstring here.

2023-02-24 18:36 UTC, joelacummings approved these changes

2023-02-28 03:43 UTC, merged